deployment:
  configuration:
    name: deploy-action-remote-e2e
    description: ""
    runtime_version: 3.1-14
    # Remote-execution deployments don't support DAG-only deploys.
    dag_deploy_enabled: false
    ci_cd_enforcement: false
    scheduler_size: SMALL
    is_high_availability: false
    is_development_mode: false
    # Remote execution requires the ASTRO executor.
    executor: ASTRO
    workspace_name: Deploy Action E2E
    deployment_type: STANDARD
    cloud_provider: AWS
    region: us-west-2
    workload_identity: ""
    remote_execution:
      enabled: true
